### ISSUE TITLE
remove all the soft-linking files

### ISSUE THREAD

**Issue by onimsha** [phuongleeo/k8s-todo#8]
I saw that you're using soft-linking for many files in the project. As my understanding that's for re-use the common files without duplicating them. I would recommend against that because following reasons:

* Modular issue: The intents of Terraform is each Terraform module can work independent to each others. With this soft-linking, if i just pick a single folder and run it outside of this whole codebase, it won't work. 
* Maintenance issue: Take an example, the `variables.tf` file contains all the possible variables, while not all modules need the same set of variables, like the case of variable `ingress-nginx` in the module `vpc`. This will create confusion for other contributors

So my recommendation is we remove all the soft-linking, and putting the actual tf files in the respective folders. I'm happy to submit a PR for this if you agree.

**Comment by phuongleeo** [comment]
> Modular issue :

The idea is: each service depends on others; before provisioning EKS, VPC must be deployed, for example. I do not quite intend to modular services. Thus I placed the `step_order.mk` file in each environment.

> Maintenance issue:

yes, the specific variable should be placed within the resources which it needs.

It would be nice if you submit a PR to me. Thanks for your feedback

**Comment by onimsha** [comment]
Here you go

**Comment by phuongleeo** [comment]
Hi, sorry for the late response.
It seems to me, your [PR](https://github.com/phuongleeo/k8s-todo/pull/9) get me wrong.

**Modular issue**: My IaC isn't intended to modular AWS services. the current structure is for a separate environment, not services by itself
eg:
the development environment contains all of the relevant resources which is depended-on each other. the purpose of VPC folder is all things of components, that are used to provision VPC resource: included tf subnet module, tf VPC module, vpc-peering stuff, and so on.

Once precision VPC provisioned, we continue with security group, IAM, keypair, EKS, RDS ,... 
the scope of `locals.tf` affects the entire environment, inside each service I placed `clustom_local.tf` in which only contains local service variables literally.

You can't copy an individual service and start applying it, caused by resource dependencies.

---
**Maintenance issue**:  yeah I knew, I should move some environment-wide variables to the local variable.
In addition, in case of a variable that is being referenced across the resource, Eg: the requirement of ingress resource: subnet ids must be tagged with cluster name of EKS. Thus symlink `locals.tf` would help us avoid error-prone, instead of duplicating local `cluster_name` in both vpc and eks.

**Comment by onimsha** [comment]
I honestly don't think so. It seems against the concept of using terraform, which is modular by design. And using symlinks in Git, although not breaking it, a practice that not many people are using (or may be i was wrong). 

I can see that you're using a workaround for the lacking of global variables concept in Terraform by using the symlinks, but i don't think it's worth to do that. But i respect your design choice and thank you for putting this project open. 

I think we can close this matter now.

**Comment by phuongleeo** [comment]
my POV is abt modular environment, not modular services. :)
and thank you for your suggestion. I'll try to simplify my IaC structure.

Can we have a chance to keep in touch? Or do you have any ideas likely open source some awesome projects? I would like to be a contributor

**Comment by onimsha** [comment]
Sure. I usually hang out with my friends in here https://t.me/geekhangout, and my Telegram handler is @onimsha . You're welcome to join .
